SERVICE_ACCOUNT_FILE = "creds/service_account.json"
SPREADSHEET_NAME = "Finance"
WORKSHEET_NAME = "Expenses"
SHEETS_API = "https://www.googleapis.com/auth/spreadsheets"
DRIVE_API = "https://www.googleapis.com/auth/drive"
SPEND_TABLE_RANGE ="A3:E3"