SPREADSHEET_NAME = "Finance"
WORKSHEET_NAME = "Expenses"
SHEETS_API = "https://www.googleapis.com/auth/spreadsheets"
DRIVE_API = "https://www.googleapis.com/auth/drive"
SPEND_TABLE_RANGE = "A3:E3"
GCP_CREDS_JSON = "GCP_CREDS_JSON"
CHART_IMAGE_URL = "CHART_IMAGE_URL"